### ISSUE TITLE
Robots that are able to bounce back into the field within a short time (1s) after completely leaving the field, should not be considered out of bounds.

### ISSUE THREAD

**Issue by teohxuen** [RoboCupJuniorTC/soccer-rules#23]
### Please describe your suggestion in one or two sentences
Robots that are able to bounce back into the field within a short time (1s) after completely leaving the field, should not be considered out of bounds.

### Please explain why do you think it should be in the rules
This increases the competitiveness of the competition by having 2 robots on the field most of the time. 
This would also be more interesting to the spectators without causing much confusion to them.This also allow teams to overcome the physical limitations of being unable to stop in time despite detecting the white line. Additionally, in real life soccer, players that are out of the field are not penalized and are able to go back into play. 

### Please list the relevant section(s) of previous rules (if applicable)
- 1.10

**Comment by mrshu** [comment]
Thank you for the suggestion @teohxuen!

It is indeed a very interesting one and I think we should certainly consider it. Before asking a few follow up questions of mine, let me give you a bit of a historical context. 

The *out of bounds* rule has been introduced (at least as far as I know) in order to reduce the ability of robots to move extremely fast on a field that is relatively small, and also to reduce "smashing into the wall", which used to be fairly common place. The price that had to be paid was that the games no longer looked like "the real life soccer" where players can leave the field without being penalized as you correctly point out. We can certainly discuss whether the *out of bounds* rule has been successful in achieving those two things (reducing speed, reducing smashing into the wall), but I wanted this historical context to be set first.

Let me know ask those few questions that we would probably need to answer in order to implement your suggestion in the rules:

1. **How would you suggest we measure the "short time" (i.e. one second)?**

I see some options here -- one would be the referee literally saying ["one thousand" / "one alligator" / "one one thousand" / "one Mississippi"](https://en.wiktionary.org/wiki/Appendix:Words_used_as_placeholders_to_count_seconds) or something similar in other languages. The other option would be to do a count of some amount (like a count of five) as currently happens by the rules in case of "out of reach" and "lack of progress".

Can you think of some other options? 

2. **Will the referees be able to handle this?**

The game is already not that simple for the referees -- they have to pay attention to a lot of stuff. I am wondering if the referees would be able to handle this rule as well. 

Specifically, I am wondering what would for instance happen if there would be two robots out of bounds on two sides on the field, and a "near-goal" situation next to one of the goals. I am not exactly sure if just two referees would be able to handle that situation (especially considering the time counting discussed above).

Do you think my worry here is premature? Did I miss something with regards to this?

3. **Suppose a robot would get out of bounds (either on its own or by being pushed out), but could not get back because a robot (from the same or opposite team) would block its way back. What should happen in situations like those?**

I am personally quite impartial here. If this is not dealt with, I could see it even becoming a fairly reasonable tactic (although strongly against the spirit of the rules and the competition in general): stay near the white line and do not let robots get in. They either get "out of bounds" (and out of the game for some time) or won't be able to do anything meaningful in the game anyway.

I do not have any good suggestions as to what should happen in those situations, so please feel free to suggest some!

-----------------------------

Once again, thank you very much for your suggestion @teohxuen. Please let's keep the discussion going (along with @RoboCupJuniorTC/soccer-tc as well)!

**Comment by felipenmartins** [comment]
Dear all,

This is a good discussion, but I think that the idea is difficult to be
properly implemented. Basically, I have the same concerns as Marek: the
referees would have a hard time detecting the "one second" and judging if
the robot is really out of bounds.

Teams are free to place their line sensors anywhere, so they should be able
to detect the line before having the robot completely out of the playing
field. The way I see it, giving them one second to be out of bounds would
not change much, because teams that already detect the line in time would
try to take advantage of this extra second, and teams that don't detect it
would care even less. Therefore, my opinion is to keep the rule as it is,
to try to force teams to come up with a more intelligent solution.

Cheers!
Felipe.



Felipe Nascimento Martins
felipe.n.martins@gmail.com
http://about.me/felipe.n.martins

**Comment by mrshu** [comment]
Thank you for the discussion everyone. As it has not moved forward since the last year, I believe we can close it now.

@teohxuen Please feel free to reopen this or any other issue in the future if you have any further comments.

Thanks!
